# Generated by Django 3.1.1 on 2020-09-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_rooms_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default=0, upload_to='property/'),
            preserve_default=False,
        ),
    ]
