# Generated by Django 3.1.1 on 2020-09-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20200917_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='adress',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
